[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "3NFnK89LbbnVrrM2EoRKirzW3ww8aC6BiU2BzfyVDc1F"

[programs.devnet]
counter = "3NFnK89LbbnVrrM2EoRKirzW3ww8aC6BiU2BzfyVDc1F"

[programs.testnet]
counter = "3NFnK89LbbnVrrM2EoRKirzW3ww8aC6BiU2BzfyVDc1F"

[programs.mainnet]
counter = "3NFnK89LbbnVrrM2EoRKirzW3ww8aC6BiU2BzfyVDc1F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "~/.config/solana/id.json"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
